"""Add v2 document intelligence tables

Revision ID: 1b3c04db7729
Revises: a65ddf83330a
Create Date: 2026-09-29 22:06:29.090969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3c04db7729'
down_revision: Union[str, None] = 'a65ddf83330a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_events',
    sa.Column('eventId', sa.String(), nullable=False),
    sa.Column('caseId', sa.String(), nullable=False),
    sa.Column('eventType', sa.String(), nullable=False),
    sa.Column('eventDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['caseId'], ['cases.caseId'], ),
    sa.PrimaryKeyConstraint('eventId')
    )
    op.create_index(op.f('ix_clinical_events_caseId'), 'clinical_events', ['caseId'], unique=False)
    op.create_index(op.f('ix_clinical_events_eventId'), 'clinical_events', ['eventId'], unique=False)
    op.create_table('evidence',
    sa.Column('evidenceId', sa.String(), nullable=False),
    sa.Column('eventId', sa.String(), nullable=True),
    sa.Column('sourceType', sa.String(), nullable=False),
    sa.Column('sourceDocumentId', sa.String(), nullable=True),
    sa.Column('snippet', sa.String(), nullable=True),
    sa.Column('pageLocation', sa.String(), nullable=True),
    sa.Column('verificationStatus', sa.String(), nullable=False),
    sa.Column('fieldPath', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['clinical_events.eventId'], ),
    sa.ForeignKeyConstraint(['sourceDocumentId'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('evidenceId')
    )
    op.create_index(op.f('ix_evidence_eventId'), 'evidence', ['eventId'], unique=False)
    op.create_index(op.f('ix_evidence_evidenceId'), 'evidence', ['evidenceId'], unique=False)
    op.add_column('documents', sa.Column('documentCategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'documentCategory')
    op.drop_index(op.f('ix_evidence_evidenceId'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_eventId'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_clinical_events_eventId'), table_name='clinical_events')
    op.drop_index(op.f('ix_clinical_events_caseId'), table_name='clinical_events')
    op.drop_table('clinical_events')
    # ### end Alembic commands ###
