"""Add v2ExtractionData to documents

Revision ID: 24c563f181d0
Revises: 1b3c04db7729
Create Date: 2026-09-29 22:16:56.162860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c563f181d0'
down_revision: Union[str, None] = '1b3c04db7729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('v2ExtractionData', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'v2ExtractionData')
    # ### end Alembic commands ###
