"""Add document intelligence fields

Revision ID: a65ddf83330a
Revises: e6cc7a5e248d
Create Date: 2026-09-29 18:46:21.209216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65ddf83330a'
down_revision: Union[str, None] = 'e6cc7a5e248d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extractedText', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('extractionStatus', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('medicalEntities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'medicalEntities')
    op.drop_column('documents', 'extractionStatus')
    op.drop_column('documents', 'extractedText')
    # ### end Alembic commands ###
