"""add_aisummary_to_cases

Revision ID: e6cc7a5e248d
Revises: 7fb2abbb2b3b
Create Date: 2026-09-28 16:35:43.977122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cc7a5e248d'
down_revision: Union[str, None] = 'b6a1d4e8c2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('aiSummary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'aiSummary')
    # ### end Alembic commands ###
